package beethoven.Generation.VerilogStub

import beethoven.AcceleratorBlackBoxCore
import beethoven.AcceleratorBlackBoxCore.VerilogPort

/** Renders the framework-owned interior of a Beethoven blackbox core's
  * `module Name ( ... );` declaration.
  *
  * The marker tokens defined here are also recognized by
  * [[VerilogStubManager]] when deciding how to update an existing file.
  * Keep them in one place so the splice and the stub agree on what
  * "marker-bracketed" looks like.
  */
private[VerilogStub] object VerilogPortRenderer {

  /** Substring that uniquely identifies the start-of-region marker.
    * The full marker line is a comment that includes this token; the
    * splicer matches by `contains(BeginToken)` rather than equality so
    * users can adjust whitespace or add inline notes if they wish.
    */
  val BeginToken: String = "BEETHOVEN-PORTS-BEGIN"
  val EndToken: String = "BEETHOVEN-PORTS-END"

  val BeginMarkerLine: String =
    s"// $BeginToken -- regenerated by Beethoven; edits inside this region will be lost"
  val EndMarkerLine: String = s"// $EndToken"

  /** All the lines that go between the framework markers (or between
    * `(` and `)` if the file has no markers yet). Includes `clock`,
    * `areset`, a blank separator, and the cmd/resp/channel ports.
    *
    * Returned as a list of fully-rendered lines (no trailing newlines)
    * so callers can re-join with whatever line separator they prefer.
    */
  def renderInteriorLines(ports: Iterable[VerilogPort]): Seq[String] = {
    val portLines = AcceleratorBlackBoxCore.getVerilogPorts(ports).split("\n").toSeq
    Seq("  input clock,", "  input areset,", "") ++ portLines
  }

  /** Marker-bracketed interior, suitable for splicing inside an existing
    * `( ... )` whose contents need to be replaced wholesale (the
    * structural-fallback path).
    *
    * Output begins and ends with newlines so the caller can drop it
    * directly between `(` and `)` without worrying about positioning.
    */
  def renderMarkerBracketedInterior(ports: Iterable[VerilogPort]): String = {
    val inner = renderInteriorLines(ports).mkString("\n")
    "\n  " + BeginMarkerLine + "\n" + inner + "\n  " + EndMarkerLine + "\n"
  }

  /** A complete fresh stub file: module declaration, marker-bracketed
    * port list, empty body. Used when no `<Name>.v` exists yet.
    */
  def renderFreshStub(
      moduleName: String,
      bbMacroParams: String,
      ports: Iterable[VerilogPort]
  ): String = {
    val interior = renderMarkerBracketedInterior(ports)
    s"""
       |module $moduleName$bbMacroParams ($interior);
       |
       |endmodule
       |""".stripMargin
  }
}
